name: Run-Lint
on: [push, pull_request]
jobs:
  lint:
    name: Run Lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.5'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest
          skip-go-installation: true
