name: Run-API-Tests
on: 
  workflow_run:
    workflows: ["Run-Lint"]
    types:
      - completed
jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Run API Tests
    runs-on: self-hosted
    needs: lint
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.5'
      - run: go test github.com/EstebanFallaGlobant/globant-golang-bootcamp/api/testapi -v -coverpkg=./...