name: Run-Unit-Tests
on: [push, pull_request]
jobs:
  test:
    name: Run Tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.5'
      - run: go test ./... -v -cover
