name: Run-Non-API-Unit-Tests
on: 
  workflow_run:
    workflows: ["Run-Lint"]
    types:
      - completed
jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Run Tests
    runs-on: self-hosted
    needs: lint
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.5'
      - run: go test ./... -v -cover
